//Auth Types
export const SET_INTRO_SLIDER = "SET_INTRO_SLIDER";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_FAILURE = "SET_LOGIN_FAILURE";
//App Types
export const SET_SELECTED_CATEGORY_DATA = "SET_SELECTED_CATEGORY_DATA";
